import {
  defineToolcraftPerformance,
  type ToolcraftPerformanceConfig,
} from "@/toolcraft/runtime";

/* Render Pipeline Inventory
   ---------------------------------------------------------------
   The reference engine (src/app/halftone.ts) exposes four addressable
   stages. Nothing below changes its algorithm; this only names the
   existing stages so control-to-pass invalidation is machine-checkable.

   decode-media      -> new Image() from the uploaded dataUrl (cached by dataUrl)
   transform-media    -> bake mediaAssets[].transform (rotate/flip) onto an
                          offscreen canvas (cached by dataUrl+transform)
   build-field        -> renderScene / readKeyField+inflate / fieldFromImage
                          (produces the per-cell lum/dep/alive Field)
   build-ramp         -> buildRamp: per-cell glyph/alpha/size tone ramp
   rasterize-glyphs   -> drawHalftone: buckets cells by tone and fillText
                          draws each bucket once per (level, pool slot)
   export-composite   -> createToolcraftPngExportCanvas render callback */
export const appPerformance: ToolcraftPerformanceConfig = defineToolcraftPerformance({
  browserCheckPolicy: {
    fallbackRunner: "playwright",
    fallbackWhen: ["agent-browser-unavailable", "ci"],
    preferredRunner: "agent-browser",
  },
  rendererPipeline: {
    interactionInvalidation: [
      {
        interaction: "media-import",
        invalidates: ["decode-media", "transform-media", "build-field", "rasterize-glyphs"],
        mustNotInvalidate: ["build-ramp"],
        targets: ["source.image"],
      },
      {
        interaction: "control-drag",
        invalidates: ["build-field", "rasterize-glyphs"],
        mustNotInvalidate: ["build-ramp", "decode-media", "transform-media"],
        targets: [
          "source.yaw",
          "source.pitch",
          "placement.zoom",
          "placement.panX",
          "placement.panY",
          "silhouette.threshold",
          "silhouette.relief",
          "silhouette.occlusion",
          "silhouette.domeRadius",
          "light.rim",
          "light.dirX",
          "light.dirY",
          "light.dirZ",
          "tone.backgroundCutoff",
          "grid.cellWidth",
          "grid.cellAspect",
        ],
      },
      {
        interaction: "control-drag",
        invalidates: ["rasterize-glyphs"],
        mustNotInvalidate: ["build-field", "build-ramp", "decode-media", "transform-media"],
        targets: [
          "tone.blackPoint",
          "tone.whitePoint",
          "tone.gamma",
          "tone.dither",
          "tone.edgeLift",
          "character.size",
        ],
      },
      {
        interaction: "control-drag",
        invalidates: ["build-ramp", "rasterize-glyphs"],
        mustNotInvalidate: ["build-field", "decode-media", "transform-media"],
        targets: ["character.variety", "character.sizeVariation", "character.sizeSteps"],
      },
      {
        interaction: "control-change",
        invalidates: ["build-field", "rasterize-glyphs"],
        mustNotInvalidate: ["build-ramp", "decode-media", "transform-media"],
        targets: ["source.mode", "source.scene", "placement.fit", "silhouette.invert", "silhouette.showMask"],
      },
      {
        interaction: "control-change",
        invalidates: ["build-ramp", "rasterize-glyphs"],
        mustNotInvalidate: ["build-field", "decode-media", "transform-media"],
        targets: ["character.mode", "character.customChars", "character.weight"],
      },
      {
        interaction: "control-change",
        invalidates: ["rasterize-glyphs"],
        mustNotInvalidate: ["build-field", "build-ramp"],
        targets: ["appearance.ink", "appearance.background", "export.includeBackground"],
      },
      {
        interaction: "control-change",
        invalidates: ["export-composite"],
        mustNotInvalidate: ["build-field", "build-ramp", "rasterize-glyphs"],
        targets: ["export.image.format", "export.image.resolution"],
      },
      {
        interaction: "export",
        invalidates: ["export-composite"],
        mustNotInvalidate: [],
        targets: ["actions.output"],
      },
      {
        interaction: "viewport-drag",
        invalidates: [],
        mustNotInvalidate: ["decode-media", "transform-media", "build-field", "build-ramp", "rasterize-glyphs"],
        targets: ["canvas.viewport"],
      },
      {
        interaction: "viewport-zoom",
        invalidates: [],
        mustNotInvalidate: ["decode-media", "transform-media", "build-field", "build-ramp", "rasterize-glyphs"],
        targets: ["canvas.viewport"],
      },
    ],
    passes: [
      {
        cacheKey: ["mediaAssets[].dataUrl"],
        id: "decode-media",
        inputs: ["source.image"],
        invalidatedBy: ["source.image"],
        kind: "decode",
        output: "source",
        quality: "full",
        runsOn: "main",
      },
      {
        cacheKey: ["mediaAssets[].dataUrl", "mediaAssets[].transform"],
        id: "transform-media",
        inputs: ["decode-media"],
        invalidatedBy: ["source.image", "media.transform"],
        kind: "preprocess",
        output: "intermediate",
        quality: "full",
        runsOn: "main",
      },
      {
        cacheKey: [
          "source.mode",
          "grid.cellWidth",
          "grid.cellAspect",
          "canvas.size.width",
          "canvas.size.height",
        ],
        id: "build-field",
        inputs: [
          "transform-media",
          "source.mode",
          "source.scene",
          "source.yaw",
          "source.pitch",
          "placement.fit",
          "placement.zoom",
          "placement.panX",
          "placement.panY",
          "silhouette.threshold",
          "silhouette.invert",
          "silhouette.showMask",
          "silhouette.domeRadius",
          "silhouette.relief",
          "silhouette.occlusion",
          "tone.backgroundCutoff",
          "light.rim",
          "light.dirX",
          "light.dirY",
          "light.dirZ",
          "grid.cellWidth",
          "grid.cellAspect",
        ],
        invalidatedBy: [
          "source.mode",
          "source.scene",
          "source.yaw",
          "source.pitch",
          "placement.fit",
          "placement.zoom",
          "placement.panX",
          "placement.panY",
          "silhouette.threshold",
          "silhouette.invert",
          "silhouette.showMask",
          "silhouette.domeRadius",
          "silhouette.relief",
          "silhouette.occlusion",
          "tone.backgroundCutoff",
          "light.rim",
          "light.dirX",
          "light.dirY",
          "light.dirZ",
          "grid.cellWidth",
          "grid.cellAspect",
          "source.image",
          "media.transform",
          "canvas.size",
        ],
        kind: "pixel-transform",
        output: "intermediate",
        quality: "full",
        runsOn: "main",
      },
      {
        cacheKey: [
          "character.mode",
          "character.customChars",
          "character.weight",
          "character.sizeVariation",
          "character.sizeSteps",
          "character.variety",
          "tone.steps",
        ],
        id: "build-ramp",
        inputs: [
          "character.mode",
          "character.customChars",
          "character.weight",
          "character.sizeVariation",
          "character.sizeSteps",
          "character.variety",
          "tone.steps",
        ],
        invalidatedBy: [
          "character.mode",
          "character.customChars",
          "character.weight",
          "character.sizeVariation",
          "character.sizeSteps",
          "character.variety",
          "tone.steps",
        ],
        kind: "text-layout",
        output: "intermediate",
        quality: "full",
        runsOn: "main",
      },
      {
        cacheKey: ["build-field", "build-ramp", "grid.cellWidth", "grid.cellAspect", "canvas.renderScale"],
        id: "rasterize-glyphs",
        inputs: [
          "build-field",
          "build-ramp",
          "character.size",
          "appearance.ink",
          "appearance.background",
          "export.includeBackground",
          "canvas.renderScale",
          "tone.backgroundCutoff",
          "tone.blackPoint",
          "tone.whitePoint",
          "tone.gamma",
          "tone.dither",
          "tone.edgeLift",
          "grid.cellWidth",
          "grid.cellAspect",
        ],
        invalidatedBy: [
          "build-field",
          "build-ramp",
          "character.size",
          "appearance.ink",
          "appearance.background",
          "export.includeBackground",
          "canvas.renderScale",
          "tone.backgroundCutoff",
          "tone.blackPoint",
          "tone.whitePoint",
          "tone.gamma",
          "tone.dither",
          "tone.edgeLift",
          "grid.cellWidth",
          "grid.cellAspect",
        ],
        kind: "rasterize",
        output: "preview",
        quality: "preview",
        runsOn: "main",
      },
      {
        cacheKey: ["export.image.resolution", "export.includeBackground"],
        id: "export-composite",
        inputs: ["rasterize-glyphs", "export.image.format", "export.image.resolution", "export.includeBackground"],
        invalidatedBy: ["export.image.format", "export.image.resolution", "export.includeBackground", "export"],
        kind: "export",
        output: "export",
        quality: "export",
        runsOn: "export-only",
      },
    ],
  },
  rendererStrategy: "canvas-2d",
  rendererTechnique: {
    exportRenderer: "canvas-2d",
    fidelityRisks: [
      "Canvas fillText anti-aliasing differs slightly across browser/OS font-rendering stacks, so glyph edges are not byte-identical across machines even though the tone math is deterministic.",
    ],
    layers: [
      {
        content: ["text"],
        exportMode: "included",
        id: "halftone-glyphs",
        kind: "product-foreground",
        primitiveCount: "high",
        renderer: "canvas-2d",
        uiSelector: '[data-toolcraft-product-output]',
      },
    ],
    performanceRisks: [
      "Large grids near the 300x300 cell cap combined with a large character set and high sizeSteps increase both the tone-ramp combination count (build-ramp) and the number of buffered fillText calls per redraw (rasterize-glyphs).",
    ],
    previewRenderer: "canvas-2d",
    productRepresentation: "text",
    rendererStrategy: "canvas-2d",
    rendererWorkload: "text-output",
    sourceRepresentation: "mixed",
    whyNotAlternativeStrategies: [
      "This is a reference-runtime clone: the user directed that src/app/halftone.ts be typed as-is and not rewritten. Its output technique is Canvas 2D ctx.font/ctx.fillText glyph drawing, not a per-pixel shader/filter, so moving to WebGL/WebGPU would replace the reference algorithm rather than preserve it.",
      "DOM/SVG text would need one node per grid cell (up to 300x300 = 90,000 nodes) and would lose the single shared canvas + font/alpha bucketing the reference engine relies on to minimize context state changes.",
    ],
  },
  rendererWorkload: "text-output",
  scenarios: [],
  usesCustomRenderer: true,
  workloadTargets: [
    "source.mode",
    "source.image",
    "character.mode",
    "character.customChars",
    "character.size",
    "character.sizeVariation",
    "character.sizeSteps",
    "character.weight",
    "silhouette.domeRadius",
    "grid.cellWidth",
    "grid.cellAspect",
    "tone.steps",
    "export.image.resolution",
  ],
});
